import ToastProvider from '@/components/ToastProvider';
import { jaJP } from '@clerk/localizations';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/appbar/Header';
import NewPost from '@/components/appbar/NewPost';
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PlayFeed',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    // <ClerkProvider>
    <ClerkProvider localization={jaJP}>
      <html lang="ja">
        <body className={inter.className}>
          <main>
            <AppRouterCacheProvider>
              <Header />
              <NewPost />
              <ToastProvider>
                {children}
              </ToastProvider>
            </AppRouterCacheProvider>
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}